name: cf_socket_client
description: "Centrifuge WebSocket client for Flutter."
version: 1.0.0
license: MIT
homepage: https://github.com/tuyen3962/cf_socket_client.git
repository: https://github.com/tuyen3962/cf_socket_client.git

environment:
  sdk: ^3.6.0
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter
  
  centrifuge: ^0.17.0
  uuid: ^4.5.3

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
